apiVersion: apps/v1
kind: Deployment
metadata:
  name: db

spec:
  replicas: 1

  selector:
    matchLabels:
      app: db

  template:
    metadata:
      labels:
        app: db

    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: notes

            - name: POSTGRES_USER
              value: notes

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: db-pvc